services:
  - type: web
    name: tokopintar
    runtime: docker
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: TOKOPINTAR
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_TIMEZONE
        value: Asia/Jakarta
      - key: APP_LOCALE
        value: id
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: FILESYSTEM_DISK
        value: public
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: tokopintar-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: tokopintar-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: tokopintar-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: tokopintar-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: tokopintar-db
          property: password

databases:
  - name: tokopintar-db
    plan: free
    region: singapore
    databaseName: tokopintar
    user: tokopintar
